# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.6
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
xcode_workspace: Example/StockInfo.xcworkspace # path to your xcodeproj folder
xcode_scheme: StockInfo
podfile: Example/Podfile
xcode_destination: platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.6
after_success:
  - bash <(curl -s https://codecov.io/bash)
