name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 11 Pro Max,OS=13.6']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Up & Testing
        run: |
          cd Example
          pod install
          xcodebuild clean test -workspace StockInfo.xcworkspace -scheme StockInfo -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.6'
